// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7vk8jpCVMdiNcS2uVKmjt6dClyzy6bw',
    appId: '1:613628797251:web:c22aad67b86bbcfb944ff6',
    messagingSenderId: '613628797251',
    projectId: 'flutterlogin-b32f3',
    authDomain: 'flutterlogin-b32f3.firebaseapp.com',
    storageBucket: 'flutterlogin-b32f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvJpOo1590-rBQJhG_GFd6F_LbRiJWGUE',
    appId: '1:613628797251:android:5cd5bd195f565dce944ff6',
    messagingSenderId: '613628797251',
    projectId: 'flutterlogin-b32f3',
    storageBucket: 'flutterlogin-b32f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSrAaNbInxGaY1ehPVXnjPJKeXqZWZxqo',
    appId: '1:613628797251:ios:a54d29e6cd387eee944ff6',
    messagingSenderId: '613628797251',
    projectId: 'flutterlogin-b32f3',
    storageBucket: 'flutterlogin-b32f3.appspot.com',
    iosClientId: '613628797251-91f07ogca0e84j38qphhs37hiejsmp37.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSrAaNbInxGaY1ehPVXnjPJKeXqZWZxqo',
    appId: '1:613628797251:ios:a54d29e6cd387eee944ff6',
    messagingSenderId: '613628797251',
    projectId: 'flutterlogin-b32f3',
    storageBucket: 'flutterlogin-b32f3.appspot.com',
    iosClientId: '613628797251-91f07ogca0e84j38qphhs37hiejsmp37.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLogin',
  );
}
